// src/components/ResponsesPage.vue
<template>
	<div class="page">
		<div id="title">
			<h1>
				Dota 2 Voice Lines
			</h1>
		</div>
		<form>
			<fieldset>
				<v-text-field 
					v-model="vars.text"
					class="ma-0"
					value=""
					placeholder="Search for text..."
					:hide-details="true"
					:clearable="true">
				</v-text-field>
				<v-autocomplete 
					v-model="vars.voice"
					:items="voices"
					item-text="text"
					item-avatar="icon"
					item-value="id"
					:hide-details="true"
					:clearable="true"
					:loading="voices.length == 0"
					placeholder="Select a hero..."
					dense>
					<template slot="item" slot-scope="data">
						<v-list-tile-avatar size="24">
							<img :src="data.item.icon">
						</v-list-tile-avatar>
						<v-list-tile-content>
							{{data.item.text}}
						</v-list-tile-content>
					</template>
					<template slot="selection" slot-scope="data">
						<v-list-tile-avatar size="24">
							<img :src="data.item.icon">
						</v-list-tile-avatar>
						<v-list-tile-content>
							{{data.item.text}}
						</v-list-tile-content>
					</template>
				</v-autocomplete>
				<v-autocomplete 
					v-model="vars.criteria"
					:items="criteria"
					item-text="text"
					item-value="value"
					:hide-details="true"
					:clearable="true"
					:loading="criteria.length == 0"
					placeholder="Select a criteria..."
					dense>
				</v-autocomplete>
			</fieldset>
		</form>
		<div>
			<Response v-for="response in responses" :response="response"></Response>
		</div>
	</div>
</template>

<script>
import dotabase from '../dotabase.js';
import utils from '../utils.js';
import Response from "./Response.vue";

export default {
	name: 'ResponsesPage',
	data() {
		return {
			voices: [],
			responses: [],
			criteria: [],
			vars: {
				text: "",
				voice: null,
				criteria: null
			}
		}
	},
	watch: {
		vars: {
			handler() {
				this.debouncedSearch();
			},
			deep: true
		}
	},
	methods: {
		search() {
			const self = this;
			var fields = "r.name, r.mp3, r.text, r.text_simple, r.criteria, r.pretty_criteria, v.icon as voice_icon";
			var query = `SELECT ${fields} FROM responses r JOIN voices v ON r.voice_id = v.id`;
			var conditions = [ "text != ''" ];
			if (this.vars.text != "") {
				// Yes i know theres sql insertion issues here. It doesnt matter, the db is readonly anyway
				conditions.push(`r.text_simple like '% ${utils.cleanText(this.vars.text)} %'`);
			}
			if (this.vars.voice != null) {
				conditions.push(`r.voice_id == ${this.vars.voice}`);
			}
			if (this.vars.criteria != null) {
				conditions.push(`(r.criteria LIKE '${this.vars.criteria}%' OR r.criteria LIKE '%|${this.vars.criteria}%')`);
			}
			query += ` WHERE ${conditions.join(" AND ")}`;
			if (this.vars.text != "") {
				query += ` ORDER BY LENGTH(text)`;
			}
			else {
				query += ` ORDER BY RANDOM()`;
			}
			query += ` LIMIT 50`;
			dotabase.query(query).then(response => {
				if (!response.success) {
					console.error(`error on query: "${response.query}"`)
					alert(`search query errored: ${response.error}`);
				}
				self.responses = response.rows;
			});
		}
	},
	created() {
		this.debouncedSearch = utils.debounce(this.search, 200);
		const self = this;
		dotabase.query("SELECT * FROM voices ORDER BY name").then(response => {
			self.voices = response.rows.map(voice => ({
				id: parseInt(voice.id),
				text: voice.name,
				icon: dotabase.vpk_path + voice.icon
			}));
		});
		dotabase.query("SELECT * FROM criteria WHERE matchkey = 'Concept'").then(response => {
			self.criteria = response.rows.map(crit => ({
				value: crit.name,
				text: crit.pretty
			}));
		});
		this.debouncedSearch();
	},
	components: {
		Response
	}
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
</style>

// src/components/pages/ResponsesPage.jsx
import React, { Component } from 'react';
import Select from 'react-select';
import VoiceSelect from '../VoiceSelect.jsx';
import dotabase from '../../Dotabase.js';
import Response from '../Response.jsx';
import '../../styles/responses.css';


function cleanText(text) {
	text = text.trim();
	text = text.toLowerCase();
	text = text.replace(/[^a-z0-9\s]/, '')
	return text;
}

function createResponseQuery(vars) {
	var fields = "r.name, r.mp3, r.text, r.text_simple, r.criteria, r.pretty_criteria, v.icon as voice_icon";
	var query = `SELECT ${fields} FROM responses r JOIN voices v ON r.voice_id = v.id`;
	var conditions = [ "text != ''" ];
	if (vars.text != "") {
		conditions.push(`text_simple like '% ${cleanText(vars.text)} %'`);
	}
	if (vars.voice != null) {
		conditions.push(`voice_id == ${vars.voice}`);
	}
	if (vars.criteria != null) {
		conditions.push(`(criteria LIKE '${vars.criteria}%' OR criteria LIKE '%|${vars.criteria}%')`);
	}
	query += ` WHERE ${conditions.join(" AND ")}`;

	if (vars.text != "") {
		query += ` ORDER BY LENGTH(text)`;
	}
	else {
		query += ` ORDER BY LENGTH(text) DESC`;
	}
	query += ` LIMIT 50`;
	return query;
}

class ResponsesPage extends Component {
	constructor(props) {
		super(props);
		this.state = {
			text: "",
			voice: null,
			criteria: null,
			criteria_options: null,
			responses: []
		};
		this.timer_id = null;

		this.updateResponses = this.updateResponses.bind(this);
		this.onSubmit = this.onSubmit.bind(this);
		this.handleChange = this.handleChange.bind(this);
		this.handleChangeTarget = this.handleChangeTarget.bind(this);
	}
	componentDidMount() {
		this.updateResponses();
		const self = this;
		dotabase.query("SELECT * FROM criteria WHERE matchkey = 'Concept'").then(response => {
			self.setState({ criteria_options: 
				response.rows.map(crit => ({
					value: crit.name,
					label: crit.pretty
				}))
			});
		});
	}
	handleChange(key, value) {
		this.setState({[key]: value});
		this.startDelayedUpdate();
	}
	handleChangeTarget(event) {
		const target = event.target;
		const value = target.type === 'checkbox' ? target.checked : target.value;
		const name = target.name;

		this.handleChange(name, value);
	}
	onSubmit(event){
		event.preventDefault();
		this.updateResponses();
	}
	updateResponses() {
		const self = this;
		dotabase.query(createResponseQuery(this.state)).then(response => {
			console.log(response.query);
			self.setState({ responses: response.rows })
		})
	}
	startDelayedUpdate() {
		const self = this;
		clearTimeout(this.timer_id);
		this.timer_id = setTimeout(() => self.updateResponses(), 300);
	}
	render() {
		return (
			<div>
				<div id={"title"}>
					<h1>
						Dota 2 Voice Lines
					</h1>
				</div>
				<form onSubmit={this.onSubmit}>
					<fieldset>
						<input
							name="text"
							type="text"
							value={this.state.text}
							onChange={this.handleChangeTarget} />
						<VoiceSelect
							name="voice"
							value={this.state.voice}
							onChange={this.handleChange} />
						<Select
							name="criteria"
							placeholder="Select a criteria..."
							value={this.state.criteria}
							onChange={(value) => this.handleChange("criteria", value && value.value)}
							options={this.state.criteria_options || []}
						/>
					</fieldset>
				</form>
				<div>
					{this.state.responses.map(response => (<Response key={response.fullname} response={response}/>))}
				</div>
			</div>
		);
	}
}

export default ResponsesPage;
