// src/components/LoadingScreen.jsx
import React, { Component } from 'react';
import dotabase from '../Dotabase.js';

class LoadingScreen extends Component {
	constructor(props) {
		super(props);
		this.state = {
			show_image: false
		};
		this.loadImageSoon = this.loadImageSoon.bind(this);
	}
	componentDidMount() {
		this.loadImageSoon();
	}
	componentWillReceiveProps(nextProps) {
		this.loadImageSoon();
	}
	loadImageSoon() {
		const self = this;
		this.setState({ show_image: false });
		setTimeout(() => self.setState({ show_image: true }), 100);
	}
	render() {
		var { screen } = this.props;
		return (
			<div className="loadingscreen-box">
				<img src={dotabase.vpk_path + screen.thumbnail}/>
				{this.state.show_image ? (<img src={dotabase.vpk_path + screen.image}/>) : null}
			</div>
		);
	}
}

export default LoadingScreen;

// src/components/LoadingScreen.vue
<template>
	<div class="loadingscreen-box">
		<img v-if="screen" :src="vpk_path + screen.thumbnail">
		<img v-if="screen && show_image" :src="vpk_path + screen.image">
	</div>
</template>

<script>
import dotabase from "../dotabase.js";

export default {
	name: 'LoadingScreen',
	props: {
		screen: {
			required: true
		}
	},
	data() {
		return {
			show_image: false,
			vpk_path: dotabase.vpk_path
		}
	},
	computed: {
		screenUrl() {
			return this.screen ? `${dotabase.vpk_path}${this.screen.thumbnail}` : "";
		}
	},
	created() {
		const self = this;
		setTimeout(() => self.show_image = true, 100);
	}
}
</script>

<style lang="scss" scoped>
</style>
